apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: techtrend
  name: techtrend
  namespace: {{ .Values.namespace.name }} 
spec:
  replicas:  {{ .Values.replicaCount }} 
  selector:
    matchLabels:
      app: techtrend
  strategy: {}
  template:
    metadata:
      labels:
        app: techtrend
    spec:
      containers:
      - image: {{ .Values.image.repository }}: {{ .Values.image.tag }}
        name: techtrend
        pullPolicy: {{ .Values.image.pullPolicy }}:
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
        livenessProbe:
          httpGet:
            path: {{ .Values.livenessProbe.path }}
            port: {{ .Values.containerPort }}
          initialDelaySeconds: 3
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: {{ .Values.readinessProbe.path }}
            port:  {{ .Values.containerPort }}
          initialDelaySeconds: 3
          periodSeconds: 5
status: {}