apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: techtrend
  name: techtrend
  namespace: sandbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: techtrend
  strategy: {}
  template:
    metadata:
      labels:
        app: techtrend
    spec:
      containers:
      - image: usuelter/techtrends:latest
        name: techtrend
        resources:
          requests:
            cpu: 250m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 128Mi
        livenessProbe:
          httpGet:
            path: /healtz
            port: 3111
          initialDelaySeconds: 3
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /healtz
            port: 3111
          initialDelaySeconds: 3
          periodSeconds: 5
status: {}