apiVersion: v1
kind: Service
metadata:
  annotations:
  name: techtrends
  namespace: sandbox
spec:
  ports:
  - name: http
    port: 4111
    protocol: TCP
    targetPort: 3111
  type: CLusterIP
status:
  loadBalancer: {}